## Task - 6 (Numpy - Both for Basic and Adv User)

### Arrays

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float

In [6]:
import os
import pandas as pd
import numpy as np
import numpy

In [9]:
def arrays(arr):
    arr1 = numpy.array(arr, dtype = float)
    arr2 = numpy.array(arr[::-1], dtype = float)
    return arr2

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### Shape and Reshape

You are given a space separated list of nine integers. Your task is to convert this list into a  3 X 3 NumPy array.

In [10]:
def arrays(arr):
    arr1 = numpy.array(arr, dtype = int)
    arr2 = arr1.reshape(3, 3)
    return arr2

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Transpose and Flatten

You are given a N X M integer array matrix with space separated elements (N = rows and M = columns).
Your task is to print the transpose and flatten results.

In [11]:
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 3
4 5
6 7
[[4 6]
 [5 7]]
[4 5 6 7]


### Concatenate

You are given two integer arrays of size N X P and M X P ( N & M  are rows, and P is the column). Your task is to concatenate the arrays along axis 0 .

In [12]:
X, Y, Z = map(int, input().split())
array = numpy.array([input().split() for i in range(X+Y)], int)

print(array)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### Zeros and Ones

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones

In [14]:
def arrays(arr):
    arr1 = numpy.array(arr, dtype = int)
    arr2 = numpy.zeros(arr1, dtype = int)
    arr3 = numpy.ones(arr1, dtype = int)
    return arr2, arr3

arr = input().strip().split(' ')
arr2, arr3 = arrays(arr)

print(arr2)
print(arr3)

4 4 4
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


### Eye and Identity

Your task is to print an array of size N X M with its main diagonal elements as 1's and 0's everywhere else.

In [15]:
numpy.set_printoptions(sign=' ')

N, M = map(int, input().split())
eye = numpy.eye(N, M)
print(eye)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Array Mathematics

You are given two integer arrays, A  and B  of dimensions  N X M.
Your task is to perform the following operations
Add ( A + B )
Subtract (A - B)
Multiply (A * B )
Integer Division (A /B )
Mod (A % B )
Power ( A ** B )

In [16]:
def arrays(arr, arr1, arr2):
    arr = numpy.array(arr, dtype = int)
    arr1 = numpy.array([arr1], dtype = int)
    arr2 = numpy.array([arr2], dtype = int)

    add = numpy.add(arr1,arr2)
    sub = numpy.subtract(arr1, arr2)
    mul = numpy.multiply(arr1, arr2)
    div = numpy.floor_divide(arr1, arr2)
    mod = numpy.mod(arr1, arr2)
    power = numpy.power(arr1, arr2)
    return add,sub,mul,div,mod,power

arr = input().strip().split(' ')

arr1 = input().strip().split(' ')
arr2 = input().strip().split(' ')
add,sub,mul,div,mod,power = arrays(arr, arr1, arr2)
print(ad
print(sub)
print(mul)
print(div)
print(mod)
print(power)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### Floor, Ceil and Rint



You are given a 1-D array,A . Your task is to print the floor , ceil  and  of all the elements of A .

In [17]:
numpy.set_printoptions(sign=' ')
def arrays(arr):
    arr1 = numpy.array(arr, dtype = float)

    floor = numpy.floor(arr1)
    ceil = numpy.ceil(arr1)
    rint = numpy.rint(arr1)

    return floor, ceil, rint    
arr = input().strip().split(' ')
floor, ceil, rint = arrays(arr)
print(floor)
print(ceil)
print(rint)

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### Sum and Prod

You are given a 2-D array with dimensions  N X M.
Your task is to perform  sum the  tool over axis 0  and then find the product of that result.

In [18]:
N, M = map(int, input().split())

array = numpy.array([input().split() for i in range(N)], int)

print(numpy.prod(numpy.sum(array, axis = 0), axis = None))


2 2
1 2
3 4
24


### Min and Max

You are given a 2-D array with dimensions N X M.
Your task is to perform the min function over axis  1 and then find the max of that.

In [19]:
N, M = map(int, input().split())

A = numpy.array([input().split() for i in range(N)],dtype = int)
print(numpy.max(numpy.min(A, axis=1), axis=0))

4 2
2 5
3 7
1 3
4 0
3


### Mean, Var, and Std

In [20]:
numpy.set_printoptions(legacy='1.13')

N, M = map(int, input().split())
A = numpy.array([input().split() for i in range(N)], dtype =int)
print(numpy.mean(A, axis =1))
print(numpy.var(A, axis =0))
print(numpy.std(A, axis = None))

2 2 
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


### Dot and Cross

You are given two arrays A  and B . Both have dimensions of N X N.
Your task is to compute their matrix product.

In [21]:
N = int(input())
A = numpy.array([input().split() for i in range(N)], dtype =int)
B = numpy.array([input().split() for i in range(N)], dtype =int)
C = numpy.dot(A,B)
print(C)

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


### Inner and Outer

You are given two arrays: A  and B .
Your task is to compute their inner and outer product.

In [22]:
a = numpy.array(input().split() , int)
b = numpy.array(input().split() , int)
print("---------------------------")
print(numpy.inner(a, b))
print("---------------------------")
print(numpy.outer(a, b))

0 1 
2 3
---------------------------
3
---------------------------
[[0 0]
 [2 3]]


### Polynomials

You are given the coefficients of a polynomial  P.
Your task is to find the value of P at point x.

In [23]:
m = numpy.array(input().split(), float)
n = float(input())
print(numpy.polyval(m, n))

1.1 2 3
0
3.0


### Linear Algebra

In [24]:
numpy.set_printoptions(legacy='1.13')

N = int(input())

A = numpy.array([input().split() for i in range(N)], float)
print(numpy.linalg.det(A))

2 
1.1 1.1
1.1 1.1
0.0
